### ISSUE TITLE
Processing cents

### ISSUE THREAD

**Issue by tsha2431** [hash-bang/PHP-SecurePay#12]
Cheers great code! But how can I process cents not just whole dollar values? I have tried sending the value in cents to securepay.php and removing `* 100` in this code `$cents = round($this->ChargeAmount * 100); // Convert to cents ` but fails.

**Comment by tsha2431** [comment]
Sorry securepay returns an error when test amount doesn't end in particular values. Your code works perfect!

**Comment by hash-bang** [comment]
Ha ha. Good to hear. Only just managed to getting around to looking at the issue.
