### ISSUE TITLE
AntiFraud

### ISSUE THREAD

**Issue by kafmil** [hash-bang/PHP-SecurePay#5]
Thanks for this, I'm using it as a library in a drupal module. I need to use antifraud for what I'm doing, so I've just added in a function that I can use to call an Antifraud (only) request. I check the results then run the normal Process function. I've created a patch that I'm using for my module which you can access here. https://www.drupal.org/files/issues/2298187-securepay_antifraud.patch

**Comment by neonblack007** [comment]
@kafmil

**Comment by hash-bang** [comment]
@neonblack007, I'm not working on it no, this library is in maintenance mode only and I doubt any further additions will be made to it.

I can't speak to whether @kafmil found a solution obviously.
